trigger:
  - develop
  - dcr_azure-pipelines_prototype
  - releases/*

pr:
  - develop

parameters:
  - name: agentVersion
    displayName: Guest Agent Version
    type: string
    default: "9.9.9.9"

variables:
  ${{ if contains( variables['Build.SourceBranchName'], 'release-' ) }}:
    agentVersion: ${{ replace(variables['Build.SourceBranchName'], 'release-', '') }}
  ${{ if eq( variables['Build.SourceBranchName'], 'develop') }}:
    agentVersion: "9.9.9.9"
  agentVersion: ${{ coalesce(variables['agentVersion'], parameters['agentVersion']) }}

jobs:

- job: DCR
  pool:
    vmImage: "ubuntu-16.04"

  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'

  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install Pip Tools'
  
  - script: python -m pip install -r requirements.txt
    displayName: 'Install WALinuxAgent dependencies'

  - script: |
      sudo ./makepkg.py
      sudo cp ./eggs/WALinuxAgent-${{variables['agentVersion']}}.zip /var/lib/waagent/
      sudo systemctl stop walinuxagent
      sudo unzip /var/lib/waagent/WALinuxAgent-${{variables['agentVersion']}}.zip \
        -d /var/lib/waagent/WALinuxAgent-${{variables['agentVersion']}}
      sudo systemctl daemon-reload && sudo systemctl start walinuxagent
    displayName: "Install latest WALinuxAgent from source"

  - script: |
    ls /usr/lib/python3/dist-packages/azurelinuxagent/
    python -vvv -c "import azurelinuxagent" 2>&1 | grep -vE "(clear)|(destroy)|(cleanup)"
    displayName: "Debug"

  - task: PythonScript@0
    inputs:
      scriptSource: 'filePath'
      scriptPath: '.azure-pipelines/dungeon_crawler_prototype/src/01_check_waagent_version.py'

