trigger:
  - develop
  - dcr_azure-pipelines_prototype
  - releases/*

pr:
  - develop

parameters:
  - name: agentVersion
    displayName: Guest Agent Version
    type: string
    default: "9.9.9.9"

variables:
  ${{ if contains( variables['Build.SourceBranchName'], 'release-' ) }}:
    agentVersion: ${{ replace(variables['Build.SourceBranchName'], 'release-', '') }}
  ${{ if eq( variables['Build.SourceBranchName'], 'develop') }}:
    agentVersion: "9.9.9.9"
  agentVersion: ${{ coalesce(variables['agentVersion'], parameters['agentVersion']) }}

jobs:

- job: DCR
  pool:
    vmImage: "ubuntu-16.04"

  steps:
  - checkout: self

  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install Pip Tools'
  
  - script: |
      python -m pip install -r requirements.txt
      python -m pip install -r dcr-requirements.txt
    displayName: 'Install WALinuxAgent dependencies'

  - script: |
      sudo ./makepkg.py
      sudo cp ./eggs/WALinuxAgent-${{variables['agentVersion']}}.zip /var/lib/waagent/
      sudo systemctl stop walinuxagent
      sudo unzip /var/lib/waagent/WALinuxAgent-${{variables['agentVersion']}}.zip \
        -d /var/lib/waagent/WALinuxAgent-${{variables['agentVersion']}}
      sudo systemctl daemon-reload && sudo systemctl start walinuxagent
    displayName: "Install latest WALinuxAgent from source"
  
  - script: |
      PROTOTYPE_DIR="$(pwd)/.azure-pipelines/dungeon_crawler_prototype"
      echo "##vso[task.setvariable variable=PYTHONPATH]$PYTHONPATH:/usr/lib/python3/dist-packages/:$PROTOTYPE_DIR/"
    displayName: "Update PYTHONPATH"

  - bash: |
      PROTOTYPE_DIR="$(pwd)/.azure-pipelines/dungeon_crawler_prototype"
      AGENT_BVT_DIR="dungeon_crawler/scenarios/agent-bvt"

      exitcode=0
      ls -1 "$PROTOTYPE_DIR/$AGENT_BVT_DIR/" | while read script; do
        [[ $script == *SKIP ]] && continue
        $PROTOTYPE_DIR/workflows/run_script.sh "$PROTOTYPE_DIR/$AGENT_BVT_DIR/$script"
        ((exitcode += $?))
      done
      exit $exitcode
    displayName: "Run Agent-BVT Scripts"

  - bash: |
      PROTOTYPE_DIR="$(pwd)/.azure-pipelines/dungeon_crawler_prototype"
      NOSETESTS_DIR="dungeon_crawler/scenarios/nosetests-prototype"

      nosetests --with-xunit "$PROTOTYPE_DIR/$NOSETESTS_DIR"
    displayName: "Run nosetests script"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: "xUnit"
      testResultsFiles: "./nosetests.xml"

